apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: pod-lens
spec:
  version: "{{ .TagName }}"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/sunny0826/kubectl-pod-lens/releases/download/{{ .TagName }}/pod-lens_linux_amd64.tar.gz" .TagName }}
    files:
    - from: "./pod-lens"
      to: "."
    - from: LICENSE
      to: "."
    bin: "pod-lens"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/sunny0826/kubectl-pod-lens/releases/download/{{ .TagName }}/pod-lens_darwin_amd64.tar.gz" .TagName }}
    files:
    - from: "./pod-lens"
      to: "."
    - from: LICENSE
      to: "."
    bin: "pod-lens"
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/sunny0826/kubectl-pod-lens/releases/download/{{ .TagName }}/pod-lens_darwin_arm64.tar.gz" .TagName }}
    files:
    - from: "./pod-lens"
      to: "."
    - from: LICENSE
      to: "."
    bin: "pod-lens"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/sunny0826/kubectl-pod-lens/releases/download/{{ .TagName }}/pod-lens_windows_amd64.zip" .TagName }}
    files:
    - from: "/pod-lens.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "pod-lens.exe"
  shortDescription: Show pod-related resources
  homepage: https://pod-lens.guoxudong.io
  description: |
    Find related workloads, namespace, node, service, configmap, secret,
    ingress, PVC and HPA by pod name and display them in a tree and table.
