apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment
spec:
  selector:
    matchLabels:
      app: my-nginx-deployment
  replicas: 3
  template:
    metadata:
      labels:
        app: my-nginx-deployment
    spec:
      containers:
        - name: nginx
          image: nginx:1.14
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  selector:
    app: my-nginx-deployment
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
