apiVersion: batch/v1
kind: Job
metadata:
  name: my-batch-job
spec:
  template:
    metadata:
      name: my-batch-job
    spec:
      containers:
        - name: my-batch-job-container
          image: busybox
          command: ["echo", "Hello, World!"]
      restartPolicy: Never
  backoffLimit: 4
