name: E2E Test

on:
  push:
    branches:
      - "master"
    paths:
      - '**.go'
      - '**.yaml'
      - '**.mod'
  pull_request:
    paths:
      - '**.go'
      - '**.yaml'
      - '**.mod'

env:
  # Common versions
  GO_VERSION: '1.18'

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Go build
        run: |
          make bin

      - name: Setup Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"

      - name: Test Check
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)

      - name: Test kube-system
        run: |
          echo "********************************************************************************"
          echo "Test kube-system..."
          echo "********************************************************************************"
          bin/pod-lens kube-apiserver-kind-control-plane -n kube-system

      - name: Test Deployments
        run: |
          echo "********************************************************************************"
          echo "Test Deployments..."
          echo "********************************************************************************"
          make e2e-deployment

      - name: Test StatefulSets
        run: |
          echo "********************************************************************************"
          echo "Test StatefulSets..."
          echo "********************************************************************************"
          kubectl apply -f e2e/statefulset.yaml
          kubectl rollout status statefulset/web
#          bin/pod-lens web-0

      - name: Test Jobs
        run: |
          echo "********************************************************************************"
          echo "Test Jobs..."
          echo "********************************************************************************"
          kubectl apply -f e2e/job.yaml
          kubectl wait --for=condition=complete job/my-batch-job
          bin/pod-lens my-batch-job-container