name: E2E Test

on:
  push:
    branches:
      - "master"
    paths:
      - '**.go'
      - '**.yaml'
      - '**.mod'
  pull_request:
    paths:
      - '**.go'
      - '**.yaml'
      - '**.mod'

env:
  # Common versions
  GO_VERSION: '1.18'

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Go build
        run: |
          make bin

      - name: Setup Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"

      - name: Testing
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
          
          bin/pod-lens kube-apiserver-kind-control-plane  -n kube-system
          bin/pod-lens etcd-kind-control-plane  -n kube-system
          kubectl create deployment e2e-test --image=nginx:latest
          kubectl rollout status deployment/e2e-test
          bin/pod-lens
